---
- name: Configure Ubuntu Server
  hosts: 4.180.123.56
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - update

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags:
        - update

    - name: Install Git, Nginx, and libraries
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - git
          - nginx
          - libssl-dev
          - libffi-dev
          - python3-dev
          - python3-pip
      tags:
        - install

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      tags:
        - start
